### ISSUE TITLE
3.5.4 support

### ISSUE THREAD

**Issue by Djive** [ttempleton/craft-category-groups-field#1]
### Description

Getting this
![55CDF0D2-238C-4F64-BF78-1F1C16B54B00](https://user-images.githubusercontent.com/1241189/90271583-543f1800-de5c-11ea-9574-4da13fdab228.png)

### Additional information
- Category Groups Field plugin version: 1.2.2
- Craft CMS version:3.5.4

**Comment by ttempleton** [comment]
Hi @Djive,

I just want to confirm whether this is a Category Groups field, and not a Categories field?  This appears to be the error that Craft outputs when a Categories field's source is set to a nonexistent category group (e.g. if the category group it was set to was deleted).

**Comment by Djive** [comment]
We developed project for about two month and everything worked ok. Highly using category group field
Until upgrade. ..no categories deleted or some change, we have production version working but local same but upgraded 
Getting only this error 

I contacted again developer and he said that he updated twig pack but still same issue
https://prnt.sc/u04je7

https://prnt.sc/u04l5m

**Comment by ttempleton** [comment]
That isn't a Category Groups field as provided by this plugin; this plugin's field type shows in the field type dropdown as 'Category Groups'.  I'm not sure what the 'Categories (Multiple Groups)' field type is, as 'Multiple Groups' doesn't appear anywhere in Craft's code, as far as I can tell; my best guess is that it might be some custom solution your developer has made, but in any case it's definitely not this plugin.
