### ISSUE TITLE
FR

### ISSUE THREAD

**Issue by wmdhosting** [ttempleton/craft-category-groups-field#3]
Hello!

There is a plugin.  that have  option 
Categories (multiple groups) 
A Categories input that lets you select multiple Category groups.

Now in Craft you can choose categories only from 1 source , with this you can choose from all sources

https://github.com/supercool/tools

Supercool is not updating anymore.

Is there a chance to add only this part  to your plugin.. 

Im willing to pay to add this option..

**Comment by ttempleton** [comment]
It's probably out of scope for this plugin, but I'd be happy to look at creating another plugin to do that. I'll give them a couple of weeks to state their plans for a Craft 4 release of that plugin, though, since it looks like there was an update to the Craft 3 version a few days ago.

**Comment by wmdhosting** [comment]
OK. i thinked i goes with that, to have all category group things in one plugin.. 

Few days ago. they said.. as they not developing for quite some time.... so im suprised too with this update

**Comment by ttempleton** [comment]
I'm now pursuing this in my role as a developer for @spicywebau, and I've just commented in https://github.com/supercool/tools/issues/22 so I'll close this issue in favour of that one. Hopefully they do upgrade the Tools plugin for Craft 4 soon, but if not, we will be moving ahead with at least the Categories (multiple groups) field type as a separate plugin.
